identifier: l6w73ap0u01eb3c1
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: mbs
homeFolder: /home/ollie/Codes/scouts/mbscouts
distFolder: ./dist/mbs
outDir: /home/ollie/Codes/scouts/mbscouts/dist/static
handle404: ''
allowErrorCollect: true
